#  Tensorflow Constants and Operations

In [22]:
import tensorflow as tf

# Example 1: Creating Tensors
Let's start by creating different types of tensors.

In [23]:
import tensorflow as tf

# Scalar tensor
scalar = tf.constant(5)
print("Scalar:", scalar)
print('\n')

# Vector tensor
vector = tf.constant([1, 2, 3, 4])
print("Vector:", vector)
print('\n')

# Matrix tensor
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)
print('\n')

# 3D Tensor
tensor3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Tensor:", tensor3d)


Scalar: tf.Tensor(5, shape=(), dtype=int32)


Vector: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


3D Tensor: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


#Example 2: Tensor Operations
Performing basic operations on tensors.

In [24]:
const1 = tf.constant(5)
const2 = tf.constant(6)

sum_const = tf.add(const1,const2)
print(sum_const)

print('\n')

mat1 = tf.constant([[2,3],[4,5]])
mat2 = tf.constant(4) # Brodacasting example

add_mat = tf.add(mat1,mat2)
print(add_mat)


tf.Tensor(11, shape=(), dtype=int32)


tf.Tensor(
[[6 7]
 [8 9]], shape=(2, 2), dtype=int32)


# Example 3: Matrix Multiplication
Performing matrix multiplication.

In [25]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

result = tf.matmul(matrix1, matrix2)
print("Matrix Multiplication:", result)


Matrix Multiplication: tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


# Example4: Basic Slicing on a 3D Tensor


In [26]:
# Create a 3D tensor (shape: 3x4x5)
tensor = tf.random.normal((3,4,5))
#tensor = tf.reshape(tf.range(60), (3, 4, 5))

print("Original Tensor:\n", tensor)

# Slice to get the first two matrices
sliced_tensor = tensor[:2]
print("Sliced Tensor (first two matrices):\n", sliced_tensor)


Original Tensor:
 tf.Tensor(
[[[ 0.5837751  -2.4950583   0.45462063 -0.86928505 -0.2874269 ]
  [ 0.75669825  1.5642878   0.971898   -1.8541888   1.0304061 ]
  [ 0.3777889   0.3854918   0.5034067   0.64117664  1.3861266 ]
  [-0.02868406 -0.8034162  -1.8607575  -0.23064037 -0.5932877 ]]

 [[-1.7404633   1.1608583  -0.29197443 -0.9201661  -0.0511467 ]
  [ 1.2221432   0.4467025   2.3927505  -1.3116431   0.6622092 ]
  [-0.9390406  -1.2013758   1.1907818   0.5239596  -0.27496454]
  [-0.2702396   0.02367282  1.3433384  -0.6305773  -0.9550508 ]]

 [[ 1.1377451  -0.15644623  0.6471728  -0.02229333  0.60813034]
  [ 0.02938697 -0.8388195  -0.48264658 -0.09369629 -0.50040007]
  [-1.2117181  -0.4037591   1.1996341  -0.6839649  -0.30378672]
  [ 0.08100735  0.81760913  0.10302535  0.09460048  0.16625053]]], shape=(3, 4, 5), dtype=float32)
Sliced Tensor (first two matrices):
 tf.Tensor(
[[[ 0.5837751  -2.4950583   0.45462063 -0.86928505 -0.2874269 ]
  [ 0.75669825  1.5642878   0.971898   -1.8541888   

#Example 5: Slicing with Steps


In [27]:
tensor_array = tf.random.normal((3,4,5))
print(tensor_array)
tensor_slicing = tensor_array[:,::2,:]
print(tensor_slicing)

tf.Tensor(
[[[-1.3045384  -1.5401288  -0.41344666  0.6206528   1.8714056 ]
  [-1.5329629  -0.744956    0.19866872  1.092144    0.01073946]
  [-0.25432336  1.2243942  -1.7136763  -0.3474803   2.1841648 ]
  [-0.23569135  0.49977624 -0.19190739  0.28552917 -0.6292529 ]]

 [[-1.4460562   0.9794346  -0.7734823   0.5891311   0.76968896]
  [-1.1411445   1.9700407  -0.09415074 -0.529565   -1.5712276 ]
  [ 0.5669853   0.7795074   1.1459635  -0.0683466  -0.43787977]
  [-0.88984436 -0.10690471 -1.2283305   0.27581894  0.02284078]]

 [[-0.0594421  -1.0222077  -0.23220332 -0.93342143 -0.3387679 ]
  [-1.2874434  -0.03835655  1.363701   -0.32362396  0.64152026]
  [-0.286253    0.2768468   0.5923379  -0.00835753  1.6361223 ]
  [-1.3091091   0.0887338  -0.4567417  -0.45040098  0.248493  ]]], shape=(3, 4, 5), dtype=float32)
tf.Tensor(
[[[-1.3045384  -1.5401288  -0.41344666  0.6206528   1.8714056 ]
  [-0.25432336  1.2243942  -1.7136763  -0.3474803   2.1841648 ]]

 [[-1.4460562   0.9794346  -0.7734823   0

# Example 6. Advanced Slicing with Combined Techniques


In [28]:
combined_slicing = tensor_array[1:,1:3,::2]
print("Combined Slicing Tensor (from second matrix, middle rows, every other column):\n", combined_slicing)

Combined Slicing Tensor (from second matrix, middle rows, every other column):
 tf.Tensor(
[[[-1.1411445  -0.09415074 -1.5712276 ]
  [ 0.5669853   1.1459635  -0.43787977]]

 [[-1.2874434   1.363701    0.64152026]
  [-0.286253    0.5923379   1.6361223 ]]], shape=(2, 2, 3), dtype=float32)


In [29]:
# Slicing with negative indices
negative_index_slicing = tensor_array[:, -2:, -3:]
print("Negative Index Slicing (last two rows and last three columns from each matrix):\n", negative_index_slicing)

Negative Index Slicing (last two rows and last three columns from each matrix):
 tf.Tensor(
[[[-1.7136763  -0.3474803   2.1841648 ]
  [-0.19190739  0.28552917 -0.6292529 ]]

 [[ 1.1459635  -0.0683466  -0.43787977]
  [-1.2283305   0.27581894  0.02284078]]

 [[ 0.5923379  -0.00835753  1.6361223 ]
  [-0.4567417  -0.45040098  0.248493  ]]], shape=(3, 2, 3), dtype=float32)


# Exercise Questions
## Question 1: Tensor Creation
Create a 3x3 tensor of ones and a 3x3 tensor of random values. Print both tensors.

In [30]:
tensor_ones = tf.ones((3, 3))
print("3x3 Tensor of Ones:")
print(tensor_ones)

tensor_random = tf.random.normal((3,3))
print("3x3 Tensor of Random Values:")
print(tensor_random)

3x3 Tensor of Ones:
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
3x3 Tensor of Random Values:
tf.Tensor(
[[-0.44424993  0.8359945   0.30671427]
 [ 0.02907692 -0.5153265   0.12678702]
 [ 1.4860383   1.5583391  -0.35119328]], shape=(3, 3), dtype=float32)


# Question 2: Basic Operations
Create a tensor with the values [1, 2, 3, 4, 5]. Compute the square and square root of each element in the tensor.

In [31]:
tensor_value = tf.constant([1,2,3,4,5], dtype = tf.float32) # remove dtype and check
square_tensor = tf.square(tensor_value)
square_root_tensor = tf.sqrt(tensor_value)

print("Square of each element in the tensor:")
print(square_tensor)
print('\n')
print("Square root of each element in the tensor:")
print(square_root_tensor)


Square of each element in the tensor:
tf.Tensor([ 1.  4.  9. 16. 25.], shape=(5,), dtype=float32)


Square root of each element in the tensor:
tf.Tensor([1.        1.4142135 1.7320508 2.        2.236068 ], shape=(5,), dtype=float32)


# Question 3: Reshape and Transpose
Create a 2x4 tensor and reshape it to a 4x2 tensor. Then, transpose the reshaped tensor.

In [32]:
tensor_val = tf.constant([[2,3,5,6],[4,8,9,10]])
tensor_transpose = tf.transpose(tensor_val)
print("Transposed Tensor:")
print(tensor_transpose)

Transposed Tensor:
tf.Tensor(
[[ 2  4]
 [ 3  8]
 [ 5  9]
 [ 6 10]], shape=(4, 2), dtype=int32)


# Question 4: Slicing and Indexing
Create a 4x4 tensor of integers from 1 to 16. Extract the second and third rows using slicing.

In [33]:
tensor_create = tf.constant(range(1,17))
print(tensor_create)
print('\n')

tensor_matrix = tf.reshape(tensor_create,(4,4))
print(tensor_matrix)
print('\n')
# Extraction of seond row
print(tensor_matrix[1, :])

# Extraction of third row
print(tensor_matrix[2, :])


tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], shape=(16,), dtype=int32)


tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]], shape=(4, 4), dtype=int32)


tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor([ 9 10 11 12], shape=(4,), dtype=int32)


# Question 5: Boolean Masking
Create a 1-D tensor with values from 1 to 10. Use boolean masking to extract all even numbers from the tensor.

In [34]:
tensor_range = tf.constant(range(1,11))
even_mask = tensor_range%2==0
print(even_mask)

boolean_masking_value = tf.boolean_mask(tensor_range, even_mask)
print(boolean_masking_value)


tf.Tensor([False  True False  True False  True False  True False  True], shape=(10,), dtype=bool)
tf.Tensor([ 2  4  6  8 10], shape=(5,), dtype=int32)


# Lab Exercise: Analyzing a Small Dataset Using TensorFlow Variables, Tensors, and Operations
## Objective
In this exercise, you will use TensorFlow to analyze a small dataset. You will apply the concepts of variables, tensors, and operations learned in the previous examples to perform various computations and manipulations. This exercise will simulate a real-life scenario where you need to preprocess data, perform mathematical operations, and derive insights.

## Dataset
Let's consider a small dataset representing the scores of students in three subjects: Math, Science, and English. Each row represents a student, and each column represents a subject.





| Math | Science | English |
|---|---|---|
| 85 | 90 | 78 |
| 72 | 85 | 65 |
| 90 | 88 | 92 |
| 60 | 75 | 70 |
| 95 | 85 | 85 |


# Tasks







1.  Create Tensors for the Dataset:
Create a 2D tensor to represent the scores of the students.

2.  Calculate the Average Score per Subject:
 Compute the mean score for each subject.

3. Find the Highest and Lowest Scores per Subject:
   Determine the maximum and minimum scores for each subject.

4. Normalize the Scores:
Normalize the scores to a range of 0 to 1.

5. Find Students with Scores Above a Threshold:
Identify students who scored above 80 in Math.

6. Add a New Subject:
Add scores for a new subject, History, for each student.

7. Calculate Total Score per Student:
Compute the total score for each student across all subjects.

8. Create One-Hot Encoded Representation:
Create a one-hot encoded representation of students who scored above 85 in Science.

In [35]:
# Create Tensors for the Dataset: Create a 2D tensor to represent the scores of the students.
score = tf.constant([[85,90,78], [72,85, 65], [90,88,92], [60,75,70], [95,85,85]])
print(score)

tf.Tensor(
[[85 90 78]
 [72 85 65]
 [90 88 92]
 [60 75 70]
 [95 85 85]], shape=(5, 3), dtype=int32)


In [36]:
# Calculate the Average Score per Subject: Compute the mean score for each subject.
avg_score = tf.reduce_mean(score, axis = 0)
print(avg_score)

tf.Tensor([80 84 78], shape=(3,), dtype=int32)


In [37]:
#Find the Highest and Lowest Scores per Subject: Determine the maximum and minimum scores for each subject.
max_score = tf.reduce_max(score, axis = 0)
min_score = tf.reduce_min(score, axis = 0)
print(max_score)
print(min_score)

tf.Tensor([95 90 92], shape=(3,), dtype=int32)
tf.Tensor([60 75 65], shape=(3,), dtype=int32)


In [38]:
# Normalize the Scores: Normalize the scores to a range of 0 to 1
normalize_score = (score-min_score)/(max_score-min_score)
print(normalize_score)

tf.Tensor(
[[0.71428571 1.         0.48148148]
 [0.34285714 0.66666667 0.        ]
 [0.85714286 0.86666667 1.        ]
 [0.         0.         0.18518519]
 [1.         0.66666667 0.74074074]], shape=(5, 3), dtype=float64)


In [39]:
# Find Students with Scores Above a Threshold: Identify students who scored above 80 in maths.
math_scores = score[:, 0]
students_above_80_math = tf.where(math_scores > 80)
print("\nStudents with Math Scores Above 80:\n", students_above_80_math.numpy())


Students with Math Scores Above 80:
 [[0]
 [2]
 [4]]


In [40]:
# Add a New Subject: Add scores for a new subject, History, for each student.

subject_add = tf.constant([[78],[92],[34],[67],[89]])
new_score_updated = tf.concat(values = [score, subject_add], axis = 1)
print(new_score_updated)

tf.Tensor(
[[85 90 78 78]
 [72 85 65 92]
 [90 88 92 34]
 [60 75 70 67]
 [95 85 85 89]], shape=(5, 4), dtype=int32)


In [41]:
# Calculate Total Score per Student: Compute the total score for each student across all subjects
total_score = tf.reduce_sum(new_score_updated, axis = 1, keepdims =1)
print(total_score)

tf.Tensor(
[[331]
 [314]
 [304]
 [272]
 [354]], shape=(5, 1), dtype=int32)


In [42]:
# Create One-Hot Encoded Representation for Science Scores Above 85
science_scores = score[:, 1]
students_above_85_science = tf.where(science_scores > 85)
one_hot_above_85_science = tf.one_hot(students_above_85_science, depth=3)
print(students_above_85_science)
print(one_hot_above_85_science)

tf.Tensor(
[[0]
 [2]], shape=(2, 1), dtype=int64)
tf.Tensor(
[[[1. 0. 0.]]

 [[0. 0. 1.]]], shape=(2, 1, 3), dtype=float32)
